eureka:
  client:
    enabled: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    ### healthcheck
    healthcheck:
      enabled: true

### this application info
server: 
  port: 8086
  
##↓に記号を入れると（"-","_"等）ロードバランシング時の名前解決時に何故かURIパースでホスト名がnullになりエラーになった。
spring:
  application:
    name: schoolService

## for Histrix
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    